Repository baileydunning/crate, pull requests merged in 2021-02, with the labels that each got.

#35 Add seeds
  code/api/package-lock.json
  code/api/package.json
  code/api/src/migrations/5-add-style-preference-to-user.js
  code/api/src/migrations/6-add-columns-to-products.js
  code/api/src/modules/product/model.js
  code/api/src/modules/product/mutations.js
  code/api/src/modules/product/resolvers.js
  code/api/src/modules/product/types.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/types.js
  code/api/src/seeders/2-products.js
  code/api/src/seeders/3-crates.js
  code/mobile/package-lock.json
  code/web/package-lock.json
Labels: backend

#43 Feature/post style
  .DS_Store
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/query.js
  code/api/src/seeders/2-products.js
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/crate/Item.js
  code/web/src/modules/crate/api/actions.js
  code/web/src/modules/product/api/actions.js
  code/web/src/modules/product/api/state.js
  code/web/src/modules/subscription/api/actions.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/StyleSurvey.js
  code/web/src/modules/user/StyleSurvey.test.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/modules/user/api/state.test.js
  code/web/src/setup/store.js
Labels: frontend

#45 Tdd/style survey
  code/api/src/modules/user/model.js
  code/web/package-lock.json
  code/web/package.json
  code/web/src/cypress.json
  code/web/src/cypress/fixtures/example.json
  code/web/src/cypress/integration/App_spec.js
  code/web/src/cypress/plugins/index.js
  code/web/src/cypress/support/commands.js
  code/web/src/cypress/support/index.js
Labels: tdd
